export const MAJORS: string[] = [
  // Computer Science & Engineering
  'Computer Science',
  'Computer Engineering',
  'Software Engineering',
  'Data Science',
  'Artificial Intelligence',
  'Cybersecurity',
  'Information Technology',
  'Information Systems',
  'Human-Computer Interaction',
  // Engineering
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Aerospace Engineering',
  'Biomedical Engineering',
  'Industrial Engineering',
  'Environmental Engineering',
  'Materials Science and Engineering',
  'Nuclear Engineering',
  'Agricultural Engineering',
  // Natural Sciences
  'Biology',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Statistics',
  'Biochemistry',
  'Neuroscience',
  'Environmental Science',
  'Earth Sciences / Geology',
  'Astronomy',
  // Business
  'Business Administration',
  'Finance',
  'Accounting',
  'Marketing',
  'Management',
  'Entrepreneurship',
  'Supply Chain Management',
  'Economics',
  'International Business',
  'Human Resources',
  'Real Estate',
  // Social Sciences
  'Psychology',
  'Sociology',
  'Political Science',
  'International Relations',
  'Anthropology',
  'Geography',
  'Criminal Justice',
  'Social Work',
  'Public Administration',
  // Health & Medicine
  'Pre-Medicine',
  'Nursing',
  'Public Health',
  'Kinesiology',
  'Nutrition',
  'Pharmacy',
  'Physical Therapy',
  'Occupational Therapy',
  'Dental Hygiene',
  'Health Sciences',
  // Arts & Humanities
  'English',
  'History',
  'Philosophy',
  'Art History',
  'Studio Art',
  'Graphic Design',
  'Architecture',
  'Music',
  'Theatre',
  'Film Studies',
  'Creative Writing',
  'Linguistics',
  'Religious Studies',
  'Classics',
  // Communication & Media
  'Communications',
  'Journalism',
  'Public Relations',
  'Advertising',
  'Media Studies',
  'Digital Media',
  // Education
  'Elementary Education',
  'Secondary Education',
  'Special Education',
  'Early Childhood Education',
  // Law & Policy
  'Pre-Law',
  'Political Science',
  'Public Policy',
  // Agriculture & Environment
  'Agriculture',
  'Animal Science',
  'Horticulture',
  'Forestry',
  'Wildlife Biology',
  // Other
  'Undeclared',
  'Liberal Arts',
  'Interdisciplinary Studies',
]

export function searchMajors(query: string): string[] {
  if (!query.trim()) return []
  const q = query.toLowerCase()
  return MAJORS.filter((m) => m.toLowerCase().includes(q)).slice(0, 8)
}
