export const SCHOOLS: string[] = [
  // Iowa
  'Iowa State University',
  'University of Iowa',
  'University of Northern Iowa',
  // Big Ten
  'University of Michigan',
  'Michigan State University',
  'Ohio State University',
  'Penn State University',
  'University of Wisconsin-Madison',
  'University of Minnesota',
  'Purdue University',
  'Indiana University',
  'University of Illinois Urbana-Champaign',
  'Northwestern University',
  'University of Maryland',
  'Rutgers University',
  'University of Nebraska-Lincoln',
  // Ivy League
  'Harvard University',
  'Yale University',
  'Princeton University',
  'Columbia University',
  'University of Pennsylvania',
  'Brown University',
  'Dartmouth College',
  'Cornell University',
  // Top Public
  'University of California, Berkeley',
  'UCLA',
  'University of California, San Diego',
  'University of California, Davis',
  'University of California, Santa Barbara',
  'University of California, Irvine',
  'University of Texas at Austin',
  'University of Florida',
  'University of Georgia',
  'University of Washington',
  'University of Virginia',
  'University of North Carolina at Chapel Hill',
  'Georgia Institute of Technology',
  'University of California, Los Angeles',
  'Virginia Tech',
  'Texas A&M University',
  'University of Arizona',
  'Arizona State University',
  'University of Colorado Boulder',
  'Colorado State University',
  'University of Oregon',
  'Oregon State University',
  'University of Utah',
  'Brigham Young University',
  'University of Kansas',
  'Kansas State University',
  'University of Missouri',
  'University of Oklahoma',
  'Oklahoma State University',
  'University of Arkansas',
  'Iowa State University',
  // Top Private
  'Massachusetts Institute of Technology',
  'Stanford University',
  'California Institute of Technology',
  'Duke University',
  'Johns Hopkins University',
  'Vanderbilt University',
  'Rice University',
  'Notre Dame University',
  'Georgetown University',
  'Emory University',
  'Washington University in St. Louis',
  'Carnegie Mellon University',
  'University of Southern California',
  'New York University',
  'Boston University',
  'Tufts University',
  'Case Western Reserve University',
  'Tulane University',
  'Lehigh University',
  'Worcester Polytechnic Institute',
  'Rensselaer Polytechnic Institute',
  'Northeastern University',
  'Drexel University',
  'American University',
  'George Washington University',
  'Syracuse University',
  'Fordham University',
  // HBCUs
  'Howard University',
  'Spelman College',
  'Morehouse College',
  'Hampton University',
  'Tuskegee University',
  // More state schools
  'University of South Carolina',
  'Clemson University',
  'University of Alabama',
  'Auburn University',
  'University of Tennessee',
  'University of Kentucky',
  'University of Mississippi',
  'Mississippi State University',
  'Louisiana State University',
  'Tulane University',
  'University of New Mexico',
  'New Mexico State University',
  'University of Nevada, Las Vegas',
  'University of Nevada, Reno',
  'University of Hawaii',
  'University of Alaska Fairbanks',
  'University of Montana',
  'Montana State University',
  'University of Wyoming',
  'University of Idaho',
  'Boise State University',
  'University of South Dakota',
  'South Dakota State University',
  'North Dakota State University',
  'University of North Dakota',
  'University of Maine',
  'University of Vermont',
  'University of New Hampshire',
  'University of Connecticut',
  'University of Rhode Island',
  'University of Delaware',
  'University of Pittsburgh',
  'Temple University',
  'Miami University',
  'Ohio University',
  'Bowling Green State University',
  'University of Cincinnati',
  'University of Dayton',
]

export function searchSchools(query: string): string[] {
  if (!query.trim()) return []
  const q = query.toLowerCase()
  return SCHOOLS.filter((s) => s.toLowerCase().includes(q)).slice(0, 8)
}
